language: csharp
mono:
  - latest
solution: src/Rezoom.sln
install:
  - nuget restore src/Rezoom.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug src/Rezoom.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./src/Rezoom.Test/bin/Debug/Rezoom.Test.dll


